### ISSUE TITLE
Console Design

### ISSUE THREAD

**Issue by 1kingofattitude1** [lllSniperlyfelll/Visior#1]
Start of Console and The Remote Control User Interface Must have Same Dimension/Size.

**Comment by lllSniperlyfelll** [comment]
![NewMM](https://user-images.githubusercontent.com/36415182/71325855-e20a7380-2518-11ea-9fa9-f28bd91bde30.jpg)

Redesigned the Ui for Console with new required screen resolution and replaced Buttons with RadioButtons and added a description of what each option does :)
